# Generated by Django 4.1.3 on 2022-11-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.TextField()),
                ('dni', models.CharField(max_length=10)),
                ('puesto', models.CharField(max_length=20)),
                ('antiguedad', models.CharField(max_length=20)),
                ('sueldo', models.CharField(max_length=10)),
            ],
        ),
    ]
