# Generated by Django 4.1.3 on 2022-12-14 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fecha_ingreso',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
